nn:
  file:
    input: /Users/xxx/Desktop/workspace/financial-product-recommendation-system/src/main/resources/CUST_INVESTMENT.csv
    output:
      checkpoint: /Users/xxx/Desktop/workspace/financial-product-recommendation-system/output/checkpoint/
      model: /Users/xxx/Desktop/workspace/financial-product-recommendation-system/output/model/recommendation_system_model/
