nn:
  product:
    file:
      input: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/src/main/resources/products.csv
  pre-processing:
    customer:
      file:
        input: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/src/main/resources/masked_cust_hldg_stock.txt
    product:
      file:
        input: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/src/main/resources/products.csv
    file:
      output: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/output/pre-processed.csv
  processing:
    file:
      input: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/output/pre-processed.csv
      output:
        checkpoint: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/output/checkpoint/
        model: /Users/frankngai/Desktop/workspace/financial-product-recommendation-system/output/model/recommendation_system_model/
